### ISSUE TITLE
Demo UI limitations & improvement items

### ISSUE THREAD

**Issue by g2flyer** [hyperledger/fabric-private-chaincode#219]
- [X] from walk-thru
  - [x] remove warning in ledger viewer
  - [x] simplified result view proposed by marcus, rename "Auction Results" to "Auction Result: License won"

- [ ] remaining from PR #218:
  - [ ] some way to trigger a refresh (see PR #218 for some suggestions)
  - [x] auction result view also for bidders

- [ ] remaining from PR #205 (and not yet addressed by PR #217 and #218)
   - [ ] show/allow modification/change of auction id) [important when running with fabric-gateway & real peer as otherwise you have to reset the whole environment for a new auction]
  - [ ] failed txs are not distinguished in tx viewer from successful ones (certainly not a critical issue)

- [ ] collected while preparing demo
  - [x] refresh of auction results doesn't work properly when already in the view (probably a concurrency problem)
  - [ ] submitBid info might be stale as not refreshed by notification (can be fixed, though, by quickly going to auction info page and back to place bid
  - [ ] Before final result view, auction info is "stuck" in info from before initial round.  So right now the bidder knows only implicitly what the status of his bids are (i.e., what he sees before editing the bid in bid summary) and the auctioneer knows nothing about progress other than the round number.
  - [ ]  A bit confusing for debugging in browser dev tools is also that we do a getAuctionStatus failures (Uncaught in promise) with invalid params  (status.rc=5)  when no auction exists yet on the server. Only a problem on server-resets, seems there is some race condition on when the auction.clear commit happens vs the test in App.vue for `if (this.auction.id === "")`...  
- [ ] issues mentioned elsewhere ..
  - [ ] issue #229 
  - [ ] issue #234

**Comment by mbrandenburger** [comment]
> * from walk-thru
>   
>   * remove warning in ledger viewer
>   * simplified result view proposed by marcus, rename "Auction Results" to "Auction Result: License won"
> * remaining from PR #218:
>   
>   * some way to trigger a refresh (see PR #218 for some suggestions)
>   * auction result view also for bidders

These issues are covered with PR #222

**Comment by mbrandenburger** [comment]
>   * some way to trigger a refresh (see PR #218 for some suggestions)

Fixed with PR #221

**Comment by g2flyer** [comment]
> > * some way to trigger a refresh (see PR #218 for some suggestions)
> 
> Fixed with PR #221

Hmm, doesn't seem to work for me: when i just log in one tab per role before running the script and then run the script, all my UIs show the original "no auction running". For bidders i can trigger progress by switching from auction info to bid summary and back which seems to trigger a read of status; for the auctioneer it seems only potentially state-modifying actions like start/end round or logout/login triggers a reload.  Also, given that fabric-gateway doesn't have notification, (mock server) notifications wouldn't help when running with real fabric network.   So having some way to trigger (in a non-chaincode-state-modifying way) a browser state update would be useful to address both of above. But obviously not on the critical path as for the demo we can work around ...

**Comment by mbrandenburger** [comment]
Let's close this one and reopen if needed.
